<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8745" started-at="2017-09-10T22:39:57Z" finished-at="2017-09-10T22:40:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8745" started-at="2017-09-10T22:39:57Z" finished-at="2017-09-10T22:40:06Z">
      <class name="uiAotomation.homePage.TC002_VerifyInvalidLoginWithDiffData">
        <test-method status="PASS" signature="setup()[pri:0, instance:uiAotomation.homePage.TC002_VerifyInvalidLoginWithDiffData@56ac3a89]" name="setup" is-config="true" duration-ms="7064" started-at="2017-09-10T17:39:58Z" finished-at="2017-09-10T17:40:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="VerifyInvalidLogin(java.lang.String, java.lang.String)[pri:0, instance:uiAotomation.homePage.TC002_VerifyInvalidLoginWithDiffData@56ac3a89]" name="VerifyInvalidLogin" duration-ms="989" started-at="2017-09-10T17:40:05Z" data-provider="loginData" finished-at="2017-09-10T17:40:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Victor]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at uiAotomation.homePage.TC002_VerifyInvalidLoginWithDiffData.VerifyInvalidLogin(TC002_VerifyInvalidLoginWithDiffData.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyInvalidLogin -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:uiAotomation.homePage.TC002_VerifyInvalidLoginWithDiffData@56ac3a89]" name="endTest" is-config="true" duration-ms="13" started-at="2017-09-10T17:40:06Z" finished-at="2017-09-10T17:40:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- uiAotomation.homePage.TC002_VerifyInvalidLoginWithDiffData -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
